name: Check Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repository name
        id: get_repo_name
        run: echo "::set-output name=repo_name::$(basename "$(pwd)")"

      # - name: Backup
      #   uses: appleboy/ssh-action@master
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY_1 }}
      #     port: 22
      #     host: 54.79.76.161
      #     username: ubuntu
      #     script: |
      #       sudo mkdir -p /odoo/custom/addons_backup && sudo cp -rf /odoo/custom/addons/${{ steps.get_repo_name.outputs.repo_name }} /odoo/custom/addons_backup/${{ steps.get_repo_name.outputs.repo_name }}

      # - name: Copy files to remote
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: 54.79.76.161
      #     username: ubuntu
      #     key: ${{ secrets.SSH_PRIVATE_KEY_1 }}
      #     source: "."
      #     target: "/odoo/custom/addons/${{ steps.get_repo_name.outputs.repo_name }}"

      # - name: Restart - Update Odoo
      #   uses: appleboy/ssh-action@master
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY_1 }}
      #     port: 22
      #     host: 54.79.76.161
      #     username: ubuntu
      #     script: |
      #       sudo systemctl restart odoo
      #       sudo chsh -s /bin/bash odoo
      #       sudo su odoo -c 'python3 /odoo/odoo-server/odoo-bin -u ${{ steps.get_repo_name.outputs.repo_name }} -d truong --addons-path=/odoo/odoo-server/addons,/odoo/custom/addons --dev all --stop-after-init'
      # - name: Check upgrade status
      #   if: ${{ failure() }}
      #   uses: appleboy/ssh-action@master
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY_1 }}
      #     port: 22
      #     host: 54.79.76.161
      #     username: ubuntu
      #     script: |
      #       sudo cp -rf /odoo/custom/addons_backup/${{ steps.get_repo_name.outputs.repo_name }} /odoo/custom/addons
      #       sudo rm -r /odoo/custom/addons_backup/${{ steps.get_repo_name.outputs.repo_name }}
      #       sudo systemctl restart odoo
      #       sudo chsh -s /bin/bash odoo
      #       sudo su odoo -c 'python3 /odoo/odoo-server/odoo-bin -u ${{ steps.get_repo_name.outputs.repo_name }} -d truong --addons-path=/odoo/odoo-server/addons,/odoo/custom/addons --dev all --stop-after-init'
      # - id: automerge
      #   name: automerge
      #   if: ${{ success() }}
      #   uses: "pascalgn/automerge-action@v0.15.6"
      #   env:
      #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #     MERGE_LABELS: ""
      # - name: feedback
      #   if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
      #   run: |
      #     echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
      - name: Setup git config
        run: |
          git config user.name 'token-generator-app[bot]'
          git config user.email '82042599+token-generator-app[bot]@users.noreply.github.com'
      - name: Auto merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto master
